<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="MQTTnet" Version="5.2.0.1603" />
    <InternalsVisibleTo Include="HyundaiBridge.Tests" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Hosting/Web/*" />
    <EmbeddedResource Include="Hyundai/Gspa/hyundai_cipher_params.json" />
    <Content Include="Hyundai/Gspa/LICENSE" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
